name = "binance-manager"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "binance-manager"
database_id = "5fe556d5-1615-4801-84c4-52021a49c867"
migrations_dir = "migrations"